# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a3cb68a5c9873d663f4d8e80f011bebec781f2ad31f31caede3c48f5d88e91e5c9ccd32e4190fe007f658a31ac384dc946a69ac1b5ae292a397ab8c4e994fc92

test:
  secret_key_base: 61a98ba34c7a5cc84da0a6e9ffbc903890d188a867e832aa9646c5f1409d6c753140571ed35d45389562b807575a3c8a84999c546ab2b104c27dd700054439bc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
